<?php
$error = false;
Template::$content ='
            <h1> Helló! </h1>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Praesent aliquam,  justo convallis luctus rutrum, erat nulla fermentum diam, at nonummy quam  ante ac quam. Maecenas urna purus, fermentum id, molestie in, commodo  porttitor, felis. Nam blandit quam ut lacus. Quisque ornare risus quis  ligula. Phasellus tristique purus a augue condimentum adipiscing. Aenean  sagittis. Etiam leo pede, rhoncus venenatis, tristique in, vulputate at,  odio. Donec et ipsum et sapien vehicula nonummy. Suspendisse potenti. Fusce  varius urna id quam. Sed neque mi, varius eget, tincidunt nec, suscipit id,  libero. In eget purus. Vestibulum ut nisl. Donec eu mi sed turpis feugiat  feugiat. Integer turpis arcu, pellentesque eget, cursus et, fermentum ut,  sapien. Fusce metus mi, eleifend sollicitudin, molestie id, varius et, nibh.  Donec nec libero.</p>
            <h2>Alcím</h2>
              <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut suscipit   odio eget purus pulvinar mollis. Etiam elementum fermentum nibh, quis   sollicitudin justo placerat eget. Integer id neque nisl, sed rutrum   risus. Nulla tellus magna, condimentum a elementum ac, cursus ut leo.   Nunc consequat erat in felis semper consequat. Curabitur pulvinar   pharetra massa a ultrices. Maecenas massa eros, rutrum eget mollis in,   elementum eu sem. Vestibulum ante ipsum primis in faucibus orci luctus   et ultrices posuere cubilia Curae; Nullam quam mi, luctus id dictum a,   convallis vel sem. Nam pharetra diam vel enim cursus sollicitudin.   Integer facilisis lectus sit amet dui euismod at tempor sapien rutrum. </p>
              <p> Pellentesque habitant morbi tristique senectus et netus et malesuada   fames ac turpis egestas. Quisque vehicula viverra erat, a tempor neque   pulvinar laoreet. Suspendisse eget odio quis lorem tempor adipiscing sit   amet quis leo. Mauris vel leo purus. Quisque aliquet volutpat ligula   quis accumsan. Morbi sit amet turpis non erat placerat laoreet mattis   quis ipsum. Nullam cursus blandit elit, ut accumsan ante mattis non.   Aliquam eget sem eu metus elementum auctor. Suspendisse ac libero ac   nulla ullamcorper congue. Proin convallis ultrices ipsum, non hendrerit   sapien fermentum id. Nullam fermentum lacus a felis placerat a mollis   est convallis. </p>
              <p> Aliquam vehicula mattis dui, ac fringilla diam congue eu. Sed eget nisl   sed quam malesuada sodales. Pellentesque habitant morbi tristique   senectus et netus et malesuada fames ac turpis egestas. Nam sem nisl,   sagittis vitae tincidunt nec, pretium ultrices augue. Nunc blandit   pretium tincidunt. Nam erat velit, tristique et dignissim vitae, tempus   vitae erat. Aenean volutpat consequat condimentum. In vehicula   adipiscing urna sed suscipit. Phasellus eros neque, vulputate sed porta   eget, ornare sit amet nulla. Sed pulvinar condimentum ullamcorper.   Praesent ullamcorper justo ut erat feugiat ac aliquam dolor sagittis.   Aliquam lacus sem, ultricies sit amet adipiscing pellentesque, vulputate   a dui. </p>
              <p> Fusce vel tortor nec neque vulputate tempus. Integer turpis elit,   molestie eu luctus eu, varius non mauris. Donec hendrerit mattis   fringilla. Etiam pretium tortor a felis mollis gravida. Integer   tincidunt lacus aliquet ipsum condimentum iaculis. Morbi diam justo,   aliquam et vehicula vitae, dictum eget urna. In hac habitasse platea   dictumst. Ut consectetur ante in eros egestas ut gravida velit   adipiscing. Vestibulum ante ipsum primis in faucibus orci luctus et   ultrices posuere cubilia Curae; Sed nec mi ut nulla congue accumsan.   Duis est nibh, faucibus eu porta ut, pulvinar sed lorem. </p>
              <p> Duis tincidunt placerat nunc, eget ultrices enim blandit vel. Nam sed   justo non magna euismod venenatis. Phasellus sed libero nisi.   Pellentesque porta tempor arcu, ac auctor nisl scelerisque a. Aliquam id   blandit massa. Donec tortor lectus, convallis id vulputate id, varius   eget lacus. Nam eleifend odio eleifend lectus condimentum quis sagittis   neque cursus. Duis tellus tellus, pretium id sodales eu, luctus id odio.   Proin feugiat, justo nec consectetur pretium, lectus lectus adipiscing   diam, nec ornare sem lectus nec turpis. Maecenas interdum, massa sed   consectetur sagittis, massa elit eleifend lorem, ut vulputate nisi quam   non eros. Vivamus vel metus diam, fermentum mattis dolor. Praesent quis   interdum nulla. Nulla et dui velit. </p>
              <p> Ut nulla tortor, volutpat in elementum in, sollicitudin id orci. Etiam   sit amet urna massa. Nulla vitae elit arcu. Sed vehicula mi et risus   accumsan sit amet eleifend mi ultricies. Nullam nec lectus vel arcu   eleifend placerat. Aenean consectetur dapibus purus vel varius. Nulla   sodales congue massa in congue. Duis sit amet urna nibh, in aliquam   mauris. Morbi fringilla dictum massa vel scelerisque. Cras sed nibh   libero. </p>
              <p> Sed ut leo nec magna fringilla sollicitudin a sed elit. Nunc quis nibh   nisi, eget porttitor mi. Sed augue nisl, ultricies quis fringilla eu,   vehicula at leo. Morbi posuere lectus sed urna blandit eleifend. Donec   non lacus nec erat laoreet hendrerit et a justo. Aenean felis diam,   condimentum eu semper egestas, iaculis ac elit. Donec a consequat arcu.   Vivamus tortor tellus, ornare eu varius eget, scelerisque sed risus.   Vivamus tincidunt, turpis et vulputate pellentesque, elit neque volutpat   augue, non facilisis nisl mi at nunc. Curabitur laoreet enim vitae   nulla congue ultrices. Nunc ac blandit leo. Maecenas placerat facilisis   aliquam. </p>
              <p> Sed elementum augue non lectus semper mattis. Integer enim sapien,   ultrices sit amet ornare vel, placerat ac sapien. Pellentesque tempor   iaculis consequat. Suspendisse quis augue ac lectus faucibus vulputate.   Donec a nisi ut metus condimentum semper tempus sit amet metus. Nulla   facilisi. Donec tincidunt condimentum mi. Donec est sapien, sodales non   varius eget, laoreet ac sapien. Nulla a lectus quis metus imperdiet   accumsan at non odio. </p>
              <p> Phasellus pharetra orci sit amet turpis lobortis feugiat. Etiam quis mi   sem, consectetur egestas dolor. Duis sodales pretium quam ac luctus.   Phasellus congue dignissim nisl a dictum. Mauris id urna imperdiet nulla   adipiscing fringilla. Fusce sit amet leo ipsum. Pellentesque accumsan   tellus in tellus consequat et pulvinar metus faucibus. Curabitur   lobortis justo at lacus tempor in sagittis mauris viverra. Praesent ac   odio mauris, eu elementum nibh. Integer lorem justo, fermentum sed   hendrerit id, lacinia et tortor. In lorem nibh, vestibulum ac varius   sed, consequat ac urna. </p>
              <p> Class aptent taciti sociosqu ad litora torquent per conubia nostra, per   inceptos himenaeos. Vivamus nec sapien vitae nunc posuere feugiat et sed   turpis. Aenean faucibus mollis condimentum. Vestibulum placerat lacinia   semper. Phasellus eget massa urna, nec faucibus metus. Duis non ipsum   in elit tristique adipiscing id eu est. Vestibulum feugiat, odio quis   semper eleifend, arcu magna hendrerit risus, nec lobortis leo orci sed   tortor. Sed tempor ullamcorper ligula a consectetur. Nullam vitae risus a   enim malesuada iaculis nec in neque. Donec justo dolor, tincidunt eu   blandit sodales, sollicitudin sit amet sem. Etiam ut dui nec dui euismod   tincidunt. Donec condimentum bibendum lectus, id pellentesque velit   imperdiet eu. Mauris ornare fermentum velit in tempus. Quisque   dignissim, mi vel placerat sollicitudin, mi sem pretium mauris, vitae   ultrices quam lectus quis justo. Nam eu neque id est scelerisque   rhoncus. </p>
            <p>&nbsp;</p>
			';

